### ISSUE TITLE
Need to kill the terminal that vscode automatically creates before launching the new ones

### ISSUE THREAD

**Issue by FOSSforlife** [fabiospampinato/vscode-terminals#19]
Firstly, thank you for this extension. It works great for my needs. But there is one small issue. I have set up 4 terminals to launch on startup, but they show up as terminals 2-5, leaving a blank unconfigured terminal in the first position. I'd like to get rid of this first one, is there any way to do so? I've tried playing around with the autorun extension to see if I can get it to run the kill command before generating the terminals from this extension, but I've had no luck. Any help would be greatly appreciated.

**Comment by fabiospampinato** [comment]
I hate that thing too, there's been some discussion [here](https://github.com/Microsoft/vscode/issues/39137) but no solution yet, it seems they don't think it's an important enough problem 🤷‍♂️  You might want to comment on that thread as well.

My solution to this involves patching VSC so that a custom script that closes the panel is run on startup, check it out here: https://github.com/Microsoft/vscode/issues/39137#issuecomment-414127477

**Comment by icodeyou** [comment]
It's a problem for me too and this is not working for me : 
https://github.com/microsoft/vscode/issues/39137#issuecomment-414127477

I followed your steps, but I still have a new terminal that pops up everytime I launch my project
